<link rel="stylesheet" type="text/css" href="<?= BASE_ASSET; ?>css/rest.css">
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script src="<?= BASE_ASSET; ?>/float-thead/jquery.floatThead.min.js"></script>
<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+s', function assets() {
          $('#btn_save').trigger('click');
          return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
          $('#btn_cancel').trigger('click');
          return false;
      });

      $('*').bind('keydown', 'Ctrl+d', function assets() {
          $('.btn_save_back').trigger('click');
          return false;
      });
  }
   
   jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="Rest Avatar">
                     </div>
                     <!-- /.widget-rest-image -->
                     <h3 class="widget-user-username">Rest</h3>
                     <h5 class="widget-user-desc"><?= cclang('new', ['Rest']); ?></h5>
                     <hr>
                  </div>
                  <?= form_open('', [
                     'name'    => 'form_rest', 
                     'class'   => 'form-horizontal', 
                     'id'      => 'form_rest', 
                     'method'  => 'POST'
                     ]); ?>
                  <div class="form-group ">
                     <label for="table_name" class="col-sm-2 control-label">Table <i class="required">*</i></label>
                     <div class="col-sm-8">
                        <select class="form-control chosen chosen-select chosen-select-with-deselect" name="table_name" id="table_name" data-placeholder="Pilih tabel" required>
                           <option value=""></option>
                           <?php foreach ($tables as $row): ?>
                           <option value="<?= $row; ?>"><?= $row; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <?=cclang('table_is_being_for_generate'); ?>.
                        </small>
                        <span class="loading2 loading-hide"><img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> <i><?= cclang('loading_field_data'); ?></i></span>

                     </div>
                  </div>
                  <div class="form-group ">
                     <label for="subject" class="col-sm-2 control-label">Subject <i class="required">*</i></label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="<?= set_value('subject'); ?>" required>
                        <small class="info help-block">The subject of rest.</small>
                     </div>
                  </div>
                  <div class="form-group ">
                     <label for="label" class="col-sm-2 control-label">Header Required</label>
                     <div class="col-sm-8">
                        <div class="col-md-2 padding-left-0">
                          <label>
                            <input class="flat-red check page_read" type="checkbox" id="x_token" value="yes" name="x_token" checked> X-Token 
                          </label>
                        </div>
                     </div>
                  </div>

                  <hr>
                  <div class="wrapper-rest">
                    
                  </div>
                  <div class="validation_rules" style="display: none">
                     <option value="" class="<?= $this->model_rest->get_input_type(); ?>"></option>
                     <?php foreach (db_get_all_data('crud_input_validation') as $input): ?>
                       <option value="<?= $input->validation; ?>" class="<?= str_replace(',', ' ', $input->group_input ?? ''); ?>" title="<?= $input->input_able; ?>" data-placeholder="<?= $input->input_placeholder; ?>" ><?= ucwords(clean_snake_case($input->validation)); ?></option>
                      <?php endforeach; ?> 
                  </div>
                  <div class="message no-message-padding">
                  </div>
                  <div class="view-nav">
                     <button type="button" class="btn btn-flat btn-primary btn_save btn_action" id="btn_save" data-stype="stay" title="Simpan (Ctrl+s)"><i class="fa fa-save"></i> <?= cclang('save_button'); ?></button>
                     <button type="button" class="btn btn-flat btn-info btn_save btn_action btn_save_back" id="btn_save_back" data-stype="back" title="<?= cclang('save_and_go_the_list_button'); ?> (Ctrl+d)"><i class="fa fa-list"></i> <?= cclang('save_and_go_the_list_button'); ?></button>
                     <a class="btn btn-flat btn-default btn_action" id="btn_cancel" href="<?= site_url('administrator/rest'); ?>" title="Kembali ke daftar REST (Ctrl+x)"><i class="fa fa-undo"></i> <?= cclang('cancel_button'); ?></a>
                     <span class="loading loading-hide"><img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> <i><?= cclang('loading_saving_data'); ?></i></span>
                  </div>
                  <?= form_close(); ?>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<script src="<?= BASE_ASSET; ?>js/rest.js"></script>
<!-- Page script -->
<script>
$(function () {
    var request = null;
    var saving = false;
    var fieldsReady = false;
    var $form = $('#form_rest');
    var $table = $('#table_name');
    var $buttons = $('.btn_save');

    function showMessage(text, type) {
        var $message = $('.message');
        if ($.fn.printMessage) {
            $message.printMessage({message: text, type: type || 'warning'});
        } else {
            $message.attr('class', 'message alert alert-' + (type === 'success' ? 'success' : 'warning')).html(text);
        }
        $message.stop(true, true).fadeIn();
    }

    function setLoading(state) {
        $('.loading2').toggle(state);
        $('.wrapper-rest').attr('aria-busy', state ? 'true' : 'false');
        $table.prop('disabled', state).trigger('chosen:updated');
        $buttons.prop('disabled', state || !fieldsReady || saving);
    }

    function initializeFields() {
        if ($.fn.chosen) {
            $('.wrapper-rest .chosen-select').each(function () {
                if (!$(this).data('chosen')) $(this).chosen({width: '100%'});
            });
        }
        if ($.fn.iCheck) {
            $('.wrapper-rest input.flat-red').each(function () {
                if (!$(this).parent().hasClass('icheckbox_minimal-red')) {
                    $(this).iCheck({checkboxClass: 'icheckbox_minimal-red', radioClass: 'iradio_minimal-red'});
                }
            });
        }

        $('.wrapper-rest .input_type').each(function () { updateValidation($(this)); });
        $('.wrapper-rest .validation').each(function () {
            var $validation = $(this);
            var $row = $validation.closest('tr');
            var id = $row.find('.rest-id').val();
            var name = $row.find('.rest-name').val();
            var dataType = String($row.find('.rest-data-type').val() || '').toLowerCase();
            var primaryKey = $row.find('.rest-primarykey').val();
            var maxLength = parseInt($row.find('.rest-max-length').val(), 10) || 0;

            if (primaryKey != 1) {
                addValidation($validation, id, name, 'required', 'no');
                if (maxLength > 0) addValidation($validation, id, name, 'max_length', 'yes', maxLength);
            }
            if (/^(tinyint|smallint|mediumint|int|bigint|decimal|float|double|number)$/.test(dataType)) {
                addValidation($validation, id, name, 'number', 'no');
            }
        });
    }

    $table.val('').trigger('chosen:updated');
    $buttons.prop('disabled', true);

    $table.off('change.restBuilder').on('change.restBuilder', function () {
        var tableName = $.trim($(this).val());
        if (request) request.abort();
        fieldsReady = false;
        $('.message').hide();
        $('.wrapper-rest').empty();
        $buttons.prop('disabled', true);
        if (!tableName) return;

        setLoading(true);
        request = $.ajax({
            url: BASE_URL + '/administrator/rest/get_field_data/' + encodeURIComponent(tableName),
            type: 'GET',
            dataType: 'json'
        }).done(function (res) {
            if (!res || !res.success || !res.html) {
                showMessage((res && res.message) || 'Struktur tabel tidak dapat dimuat.');
                return;
            }
            $('#subject').val(res.subject || '');
            $('.wrapper-rest').html(res.html);
            initializeFields();
            fieldsReady = true;
        }).fail(function (xhr, status) {
            if (status !== 'abort') {
                var message = xhr.responseJSON && xhr.responseJSON.message ? xhr.responseJSON.message : 'Struktur tabel gagal dimuat. Silakan coba kembali.';
                showMessage(message);
            }
        }).always(function () {
            request = null;
            setLoading(false);
        });
    });

    $buttons.off('click.restBuilder').on('click.restBuilder', function () {
        if (saving || !fieldsReady) return false;
        $('.message').hide();

        if (!$table.val() || !$form.find('input[name="primary_key"]').length || !$form.find('[name^="rest["]').length) {
            showMessage('Pilih tabel yang memiliki primary key dan tunggu sampai konfigurasi field selesai dimuat.');
            return false;
        }
        if (!$form[0].checkValidity()) {
            $form[0].reportValidity();
            return false;
        }

        var saveType = $(this).data('stype');
        var data = $form.serializeArray();
        data.push({name: 'save_type', value: saveType});
        saving = true;
        $buttons.prop('disabled', true);
        $('.loading').show();

        $.ajax({url: BASE_URL + '/administrator/rest/add_save', type: 'POST', dataType: 'json', data: data})
            .done(function (res) {
                if (res && res.success) {
                    if (saveType === 'back' && res.redirect) {
                        window.location.href = res.redirect;
                        return;
                    }
                    showMessage(res.message || 'REST API berhasil dibuat.', 'success');
                } else {
                    showMessage((res && res.message) || 'REST API tidak dapat disimpan.');
                }
            })
            .fail(function (xhr) {
                var message = xhr.responseJSON && xhr.responseJSON.message ? xhr.responseJSON.message : 'Terjadi kesalahan saat menyimpan REST API.';
                showMessage(message);
            })
            .always(function () {
                saving = false;
                $('.loading').hide();
                setLoading(false);
            });
        return false;
    });

    $('#btn_cancel').off('click').on('click.restBuilder', function (event) {
        event.preventDefault();
        window.location.href = $(this).attr('href');
    });
});
</script>
