
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Waarmerking</b></h3>
                     <h5 class="widget-user-desc">Detail Waarmerking</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_waarmerking" id="form_waarmerking" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Notaris </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->nama_notaris); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Waarmerking </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->id_waarmerking); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nomor Akta </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->nomor_akta); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Akta </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->tanggal_akta); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sifat Akta </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->sifat_akta); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penghadap </label>

                        <div class="col-sm-8">
                           <?= _ent($waarmerking->penghadap); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('waarmerking_update', function() use ($waarmerking){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit waarmerking (Ctrl+e)" href="<?= site_url('waarmerking/edit/'.$waarmerking->id_waarmerking); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Waarmerking']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('waarmerking/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Waarmerking']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
