
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Laporan Bulanan</b></h3>
                     <h5 class="widget-user-desc">Detail Laporan Bulanan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_laporan_bulanan" id="form_laporan_bulanan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Laporan Bulanan </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan_bulanan->id_laporan_bulanan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan_bulanan->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Laporan </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan_bulanan->tanggal_laporan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> File Laporan </label>
                        <div class="col-sm-8">
                             <?php if (is_image($laporan_bulanan->file_laporan)): ?>
                              <a href="<?= site_url('report-preview/preview/laporan-bulanan/' . $laporan_bulanan->id_laporan_bulanan); ?>" title="Pratinjau dokumen">
                                <img src="<?= BASE_URL . 'uploads/laporan_bulanan/' . $laporan_bulanan->file_laporan; ?>" class="image-responsive" alt="image laporan_bulanan" title="file_laporan laporan_bulanan" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= site_url('report-preview/preview/laporan-bulanan/' . $laporan_bulanan->id_laporan_bulanan); ?>" title="Pratinjau dokumen">
                                 <img src="<?= get_icon_file($laporan_bulanan->file_laporan); ?>" class="image-responsive" alt="image laporan_bulanan" title="file_laporan <?= $laporan_bulanan->file_laporan; ?>" width="40px"> 
                               <?= _ent($laporan_bulanan->file_laporan); ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kd Wilayah </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan_bulanan->nama_wilayah); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('laporan_bulanan_update', function() use ($laporan_bulanan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit laporan_bulanan (Ctrl+e)" href="<?= site_url('laporan_bulanan/edit/'.$laporan_bulanan->id_laporan_bulanan); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Laporan Bulanan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('laporan_bulanan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Laporan Bulanan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
