
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Setup Satker</b></h3>
                     <h5 class="widget-user-desc">Detail Setup Satker</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_setup_satker" id="form_setup_satker" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Satker </label>

                        <div class="col-sm-8">
                           <?= _ent($setup_satker->id_satker); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Satker </label>

                        <div class="col-sm-8">
                           <?= _ent($setup_satker->nama_satker); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('setup_satker_update', function() use ($setup_satker){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit setup_satker (Ctrl+e)" href="<?= site_url('setup_satker/edit/'.$setup_satker->id_satker); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Setup Satker']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('setup_satker/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Setup Satker']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
