
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Rekap Laporan</b></h3>
                     <h5 class="widget-user-desc">Detail Rekap Laporan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_rekap_Laporan" id="form_rekap_Laporan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Laporan </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->Tanggal_Laporan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Laporan </label>
                        <div class="col-sm-8">
                             <?php if (is_image($rekap_Laporan->Laporan)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/rekap_Laporan/' . $rekap_Laporan->Laporan; ?>">
                                <img src="<?= BASE_URL . 'uploads/rekap_Laporan/' . $rekap_Laporan->Laporan; ?>" class="image-responsive" alt="image rekap_Laporan" title="Laporan rekap_Laporan" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/rekap_Laporan/' . $rekap_Laporan->Laporan; ?>">
                                 <img src="<?= get_icon_file($rekap_Laporan->Laporan); ?>" class="image-responsive" alt="image rekap_Laporan" title="Laporan <?= $rekap_Laporan->Laporan; ?>" width="40px"> 
                               <?= $rekap_Laporan->Laporan ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('rekap_Laporan_update', function() use ($rekap_Laporan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit rekap_Laporan (Ctrl+e)" href="<?= site_url('rekap_Laporan/edit/'.$rekap_Laporan->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Rekap Laporan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('rekap_Laporan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Rekap Laporan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
