
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Rekap Laporan</b></h3>
                     <h5 class="widget-user-desc">Detail Rekap Laporan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_rekap_Laporan" id="form_rekap_Laporan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Laporan </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_Laporan->Tanggal_Laporan); ?>
                        </div>
                    </div>
                                         
                    <?php
                    $document_name = (string) $rekap_Laporan->Laporan;
                    $document_url = BASE_URL . 'uploads/rekap_Laporan/' . rawurlencode($document_name);
                    $document_extension = strtolower(pathinfo($document_name, PATHINFO_EXTENSION));
                    $office_document = in_array($document_extension, ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'], true);
                    $preview_url = $office_document
                        ? 'https://view.officeapps.live.com/op/embed.aspx?src=' . rawurlencode($document_url)
                        : $document_url;
                    ?>
                    <div class="form-group report-document-field">
                        <label class="col-sm-2 control-label">Dokumen Laporan</label>
                        <div class="col-sm-10">
                            <div class="report-document-preview">
                                <div class="report-document-toolbar">
                                    <div class="report-document-name"><i class="fa fa-file-text-o"></i><span><?= _ent($document_name); ?></span></div>
                                    <div class="report-document-actions">
                                        <a href="<?= _ent($preview_url); ?>" target="_blank" rel="noopener" class="btn btn-default"><i class="fa fa-external-link"></i> Buka tab baru</a>
                                        <a href="<?= _ent($document_url); ?>" download class="btn btn-primary"><i class="fa fa-download"></i> Unduh</a>
                                    </div>
                                </div>
                                <?php if (is_image($document_name)): ?>
                                    <div class="report-document-image"><img src="<?= _ent($document_url); ?>" alt="Pratinjau dokumen rekap laporan"></div>
                                <?php elseif ($document_extension === 'pdf' || $office_document): ?>
                                    <iframe src="<?= _ent($preview_url); ?>" title="Pratinjau <?= _ent($document_name); ?>"></iframe>
                                <?php else: ?>
                                    <div class="report-document-unavailable"><i class="fa fa-file-o"></i><strong>Pratinjau belum tersedia untuk format ini.</strong><span>Gunakan tombol Unduh untuk membuka dokumen.</span></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('rekap_Laporan_update', function() use ($rekap_Laporan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit rekap_Laporan (Ctrl+e)" href="<?= site_url('rekap_Laporan/edit/'.$rekap_Laporan->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Rekap Laporan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('rekap_Laporan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Rekap Laporan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
