
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Laporan</b></h3>
                     <h5 class="widget-user-desc">Detail Laporan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_laporan" id="form_laporan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Notaris </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan->nama_notaris); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Laporan </label>

                        <div class="col-sm-8">
                           <?= _ent($laporan->Tanggal_Laporan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Laporan </label>
                        <div class="col-sm-8">
                             <?php if (is_image($laporan->Laporan)): ?>
                              <a href="<?= site_url('document/preview/laporan/' . $laporan->id); ?>" title="Pratinjau dokumen">
                                <img src="<?= BASE_URL . 'uploads/laporan/' . $laporan->Laporan; ?>" class="image-responsive" alt="image laporan" title="Laporan laporan" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= site_url('document/preview/laporan/' . $laporan->id); ?>" title="Pratinjau dokumen">
                                 <img src="<?= get_icon_file($laporan->Laporan); ?>" class="image-responsive" alt="image laporan" title="Laporan <?= $laporan->Laporan; ?>" width="40px"> 
                               <?= _ent($laporan->Laporan); ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('laporan_update', function() use ($laporan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit laporan (Ctrl+e)" href="<?= site_url('laporan/edit/'.$laporan->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Laporan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('laporan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Laporan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
