
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Data Notaris</b></h3>
                     <h5 class="widget-user-desc">Detail Data Notaris</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_data_notaris" id="form_data_notaris" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Notaris </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->id_notaris); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Notaris </label>

                        <div class="col-sm-8">
                           <div class="notaris-name-cell">
                             <?php if (!empty($data_notaris->foto)): ?>
                               <?php if (is_image($data_notaris->foto)): ?>
                               <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/data_notaris/' . $data_notaris->foto; ?>">
                                 <img src="<?= BASE_URL . 'uploads/data_notaris/' . $data_notaris->foto; ?>" class="notaris-name-cell__photo" alt="Foto <?= _ent($data_notaris->nama_notaris); ?>" title="foto data_notaris">
                               </a>
                               <?php else: ?>
                               <a href="<?= BASE_URL . 'administrator/file/download/data_notaris/' . $data_notaris->foto; ?>">
                                 <img src="<?= get_icon_file($data_notaris->foto); ?>" class="notaris-name-cell__photo" alt="Foto <?= _ent($data_notaris->nama_notaris); ?>" title="foto <?= $data_notaris->foto; ?>">
                               </a>
                               <?php endif; ?>
                             <?php endif; ?>
                             <span><?= _ent($data_notaris->nama_notaris); ?></span>
                           </div>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->tempat_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent(format_date_id($data_notaris->tanggal_lahir)); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->jenis_kelamin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Wilayah </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->nama_wilayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Surat Pindah </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->surat_pindah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Surat Keputusan </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->surat_keputusan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat Rumah </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->alamat_rumah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat Kantor </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->alamat_kantor); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Password </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->password); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Wilayah </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->nama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lat </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->lat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Telepon </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->no_telepon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Long </label>

                        <div class="col-sm-8">
                           <?= _ent($data_notaris->long); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('data_notaris_update', function() use ($data_notaris){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit data_notaris (Ctrl+e)" href="<?= site_url('data_notaris/edit/'.$data_notaris->id_notaris); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Data Notaris']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('data_notaris/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Data Notaris']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
