
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>

<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><b>Rekap Laporan Bulanan</b></h3>
                     <h5 class="widget-user-desc">Detail Rekap Laporan Bulanan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_rekap_laporan_bulanan" id="form_rekap_laporan_bulanan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Laporan Bulanan </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_laporan_bulanan->id_laporan_bulanan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Username </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_laporan_bulanan->username); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Laporan </label>

                        <div class="col-sm-8">
                           <?= _ent($rekap_laporan_bulanan->tanggal_laporan); ?>
                        </div>
                    </div>
                                         
                    <?php
                    $document_name = (string) $rekap_laporan_bulanan->file_laporan;
                    $document_url = BASE_URL . 'uploads/rekap_laporan_bulanan/' . rawurlencode($document_name);
                    $viewer_url = google_document_viewer_url($document_url);
                    ?>
                    <div class="form-group report-document-field">
                        <label class="col-sm-2 control-label">Dokumen Laporan</label>
                        <div class="col-sm-10">
                            <div class="report-document-links">
                                <a href="<?= _ent($viewer_url); ?>" target="_blank" rel="noopener noreferrer" class="report-drive-link" title="Buka dokumen di Google Drive">
                                    <img src="<?= _ent(get_icon_file($document_name)); ?>" alt="Dokumen rekap laporan bulanan">
                                    <span><strong><?= _ent($document_name); ?></strong><small>Buka di Google Drive <i class="fa fa-external-link"></i></small></span>
                                </a>
                                <a href="<?= _ent($document_url); ?>" download="<?= _ent($document_name); ?>" class="report-download-link" title="Unduh dokumen"><i class="fa fa-download"></i> Unduh</a>
                            </div>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('rekap_laporan_bulanan_update', function() use ($rekap_laporan_bulanan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit rekap_laporan_bulanan (Ctrl+e)" href="<?= site_url('rekap_laporan_bulanan/edit/'.$rekap_laporan_bulanan->id_laporan_bulanan); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Rekap Laporan Bulanan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('rekap_laporan_bulanan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Rekap Laporan Bulanan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
