<!-- Fine Uploader Gallery CSS file
====================================================================== -->
<link href="<?= BASE_ASSET; ?>/fine-upload/fine-uploader-gallery.min.css" rel="stylesheet">
<!-- Fine Uploader jQuery JS file
====================================================================== -->
<script src="<?= BASE_ASSET; ?>/fine-upload/jquery.fine-uploader.js"></script>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+s', function assets() {
      $('#btn_save').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_cancel').trigger('click');
       return false;
   });

  $('*').bind('keydown', 'Ctrl+d', function assets() {
      $('.btn_save_back').trigger('click');
       return false;
   });
    
}

jQuery(document).ready(domo);
</script>
<?php $this->load->view('core_template/fine_upload'); ?>

<!-- Main content -->
<section class="content fidusia-form-page user-registry-form-page">
  <div class="fidusia-form-shell">
    <header class="fidusia-form-header">
      <div class="fidusia-form-header__copy">
        <span class="fidusia-form-header__icon"><i class="fa fa-user-plus" aria-hidden="true"></i></span>
        <div><span class="fidusia-form-eyebrow">MANAJEMEN PENGGUNA</span><h1>Tambah Pengguna</h1><p>Buat akun, tentukan wilayah kerja, dan atur kelompok akses pengguna.</p></div>
      </div>
      <span class="fidusia-form-status"><i class="fa fa-file-o" aria-hidden="true"></i>Data baru</span>
    </header>
    <?= form_open('', ['name' => 'form_user', 'class' => 'fidusia-form user-registry-form', 'id' => 'form_user', 'enctype' => 'multipart/form-data', 'method' => 'POST']); ?>
      <div class="message fidusia-form-message"></div>
      <div class="fidusia-form-grid">
        <section class="fidusia-form-card">
          <div class="fidusia-form-card__heading"><span><i class="fa fa-user"></i></span><div><h2>Identitas Akun</h2><p>Informasi utama yang digunakan pengguna untuk mengakses SILARIS.</p></div></div>
          <div class="fidusia-form-fields fidusia-form-fields--document">
            <div class="fidusia-form-field"><label for="username">Username <i class="required">*</i></label><input type="text" class="form-control" name="username" id="username" minlength="3" maxlength="100" pattern="[A-Za-z0-9._-]+" autocomplete="username" required placeholder="Contoh: nama.pengguna" value="<?= _ent(set_value('username')); ?>"><small><i class="fa fa-info-circle"></i>3–100 karakter: huruf, angka, titik, garis bawah, atau tanda hubung.</small></div>
            <div class="fidusia-form-field"><label for="email">Email <i class="required">*</i></label><input type="email" class="form-control" name="email" id="email" maxlength="100" autocomplete="email" required placeholder="nama@contoh.go.id" value="<?= _ent(set_value('email')); ?>"><small><i class="fa fa-envelope-o"></i>Gunakan alamat email aktif dan unik.</small></div>
            <div class="fidusia-form-field"><label for="full_name">Nama Lengkap <i class="required">*</i></label><input type="text" class="form-control" name="full_name" id="full_name" maxlength="200" required placeholder="Nama lengkap beserta gelar" value="<?= _ent(set_value('full_name')); ?>"><small><i class="fa fa-user"></i>Nama ini akan ditampilkan pada sistem.</small></div>
            <div class="fidusia-form-field"><label for="phone_number">Nomor Telepon <i class="required">*</i></label><input type="tel" class="form-control" name="phone_number" id="phone_number" inputmode="numeric" minlength="10" maxlength="13" pattern="08[0-9]{8,11}" autocomplete="tel" required placeholder="Contoh: 081234567890" value="<?= _ent(set_value('phone_number')); ?>"><small><i class="fa fa-phone"></i>Gunakan 10–13 digit dalam format 08xxxxxxxxxx.</small></div>
            <div class="fidusia-form-field fidusia-form-field--full"><label for="password">Kata Sandi <i class="required">*</i></label><div class="input-group input-password"><input type="password" class="form-control password" name="password" id="password" minlength="8" maxlength="72" autocomplete="new-password" required placeholder="Minimal 8 karakter" value=""><span class="input-group-btn"><button type="button" class="btn btn-flat show-password" aria-label="Tampilkan kata sandi"><i class="fa fa-eye eye"></i></button></span></div><small><i class="fa fa-lock"></i>Gunakan 8–72 karakter.</small></div>
          </div>
        </section>
        <section class="fidusia-form-card">
          <div class="fidusia-form-card__heading"><span><i class="fa fa-shield"></i></span><div><h2>Wilayah dan Hak Akses</h2><p>Tentukan cakupan kerja dan kewenangan akun.</p></div></div>
          <div class="fidusia-form-fields fidusia-form-fields--document">
            <div class="fidusia-form-field"><label for="kd_wilayah">Wilayah Kerja <i class="required">*</i></label><select class="form-control chosen chosen-select-deselect" name="kd_wilayah" id="kd_wilayah" data-placeholder="Pilih wilayah kerja" required><option value=""></option><?php foreach (db_get_all_data('wilayah') as $row): ?><option value="<?= _ent($row->kd_wilayah); ?>" <?= set_select('kd_wilayah', $row->kd_wilayah); ?>>[ <?= _ent($row->kd_wilayah); ?> ] <?= _ent($row->nama); ?></option><?php endforeach; ?></select><small><i class="fa fa-map-marker"></i>Pilih kabupaten/kota tempat pengguna bertugas.</small></div>
            <div class="fidusia-form-field"><label for="group">Kelompok Akses <i class="required">*</i></label><select class="form-control chosen chosen-select" name="group[]" id="group" multiple required data-placeholder="Pilih kelompok akses"><?php foreach (get_application_groups() as $row): ?><option value="<?= (int) $row->id; ?>" <?= set_select('group[]', $row->id); ?>><?= _ent(ucwords($row->name)); ?></option><?php endforeach; ?></select><small><i class="fa fa-users"></i>Pilih satu atau beberapa kelompok akses.</small></div>
            <div class="fidusia-form-field fidusia-form-field--full user-registry-guidance-list" id="registry-group-guidance" hidden>
              <div class="alert alert-info user-registry-guidance" data-group-guidance="notaris" hidden><strong>Data Notaris:</strong> setelah akun disimpan, lengkapi identitas, dokumen, wilayah kerja, dan statusnya melalui menu Setup → Data Notaris.</div>
              <div class="alert alert-info user-registry-guidance" data-group-guidance="mpd" hidden><strong>Data MPD:</strong> setelah akun disimpan, lengkapi identitas, verifikasi, dan wilayah pengawasannya melalui menu Setup → Data MPD.</div>
            </div>
            <div class="fidusia-form-field fidusia-form-field--full"><label for="user_avatar_galery">Foto Profil</label><div id="user_avatar_galery"></div><input name="user_avatar_uuid" id="user_avatar_uuid" type="hidden" value="<?= _ent(set_value('user_avatar_uuid')); ?>"><input name="user_avatar_name" id="user_avatar_name" type="hidden" value="<?= _ent(set_value('user_avatar_name')); ?>"><small><i class="fa fa-image"></i>Gunakan berkas PNG atau JPEG.</small></div>
          </div>
        </section>
      </div>
      <footer class="fidusia-form-actions"><div class="fidusia-form-actions__hint"><i class="fa fa-info-circle"></i><span>Pastikan email, wilayah, dan kelompok akses sudah benar.</span></div><div class="fidusia-form-actions__buttons"><a class="btn admin-button admin-button--neutral btn_action" id="btn_cancel"><i class="fa fa-times"></i> Batal</a><button class="btn admin-button admin-button--secondary btn_save btn_action btn_save_back" type="button" data-stype="back"><i class="fa fa-list"></i> Simpan & kembali</button><button class="btn admin-button admin-button--save btn_save btn_action" id="btn_save" type="button" data-stype="stay"><i class="fa fa-save"></i> Simpan Pengguna</button><span class="loading loading-hide"><img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> <i><?= cclang('loading_saving_data'); ?></i></span></div></footer>
    <?= form_close(); ?>
  </div>
</section>
<!-- /.content -->


<script src="<?= BASE_ASSET; ?>ckeditor/ckeditor.js"></script>
<!-- Page script -->
<script>
  $(document).ready(function() {
    $('#btn_cancel').click(function() {
        swal({
                title: "Are you sure?",
                text: "the data that you have created will be in the exhaust!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes!",
                cancelButtonText: "No!",
                closeOnConfirm: true,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    window.location.href = BASE_URL + 'administrator/user';
                }
            });

        return false;
    }); /*end btn cancel*/

    $('.btn_save').click(function() {
        $('.message').fadeOut();

        var form_user = $('#form_user');
        var data_post = form_user.serializeArray();
        var save_type = $(this).attr('data-stype');

        data_post.push({
            name: 'save_type',
            value: save_type
        });

        $('.loading').show();

        data_post.group = $('#group').chosen().val();

        $.ajax({
                url: BASE_URL + '/administrator/user/add_save',
                type: 'POST',
                dataType: 'json',
                data: data_post,
            })
            .done(function(res) {
                if (res.success) {
                    var id = $('#user_avatar_galery').find('li').attr('qq-file-id');

                    if (save_type == 'back') {
                        window.location.href = res.redirect;
                        return;
                    }

                    $('.message').printMessage({
                        message: res.message
                    });
                    $('.message').fadeIn();
                    $('form input[type != hidden], form textarea, form select').val('');
                    $('.chosen').val('').trigger('chosen:updated');
                    $('#user_avatar_galery').fineUploader('deleteFile', id);

                } else {
                    $('.message').printMessage({
                        message: res.message,
                        type: 'warning'
                    });
                    $('.message').fadeIn();
                }

            })
            .fail(function() {
                $('.message').printMessage({
                    message: 'Error save data',
                    type: 'warning'
                });
            })
            .always(function() {
                $('.loading').hide();
                $('html, body').animate({
                    scrollTop: $(document).height()
                }, 1000);
            });

        return false;
    }); /*end btn save*/

    $('#user_avatar_galery').fineUploader({
        template: 'qq-template-gallery',
        request: {
            endpoint: BASE_URL + '/administrator/user/upload_avatar_file',
            params: {
                '<?= $this->security->get_csrf_token_name(); ?>': '<?=   $this->security->get_csrf_hash(); ?>'
            }
        },
        deleteFile: {
            enabled: true,
            endpoint: BASE_URL + '/administrator/user/delete_avatar_file'
        },
        thumbnails: {
            placeholders: {
                waitingPath: BASE_URL + '/asset/fine-upload/placeholders/waiting-generic.png',
                notAvailablePath: BASE_URL + '/asset/fine-upload/placeholders/not_available-generic.png'
            }
        },
        multiple: false,
        validation: {
            allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
            sizeLimit: 5 * 1024 * 1024
        },
        showMessage: function(msg) {
            toastr['error'](msg);
        },
        callbacks: {
            onComplete: function(id, name, responseJSON) {
                if (!responseJSON.success) {
                    $('#user_avatar_uuid').val('');
                    $('#user_avatar_name').val('');
                    return;
                }
                var uuid = $('#user_avatar_galery').fineUploader('getUuid', id);
                $('#user_avatar_uuid').val(uuid);
                $('#user_avatar_name').val(responseJSON.uploadName || name);
            },
            onSubmit: function(id, name) {
                var uuid = $('#user_avatar_uuid').val();
                $.get(BASE_URL + '/administrator/user/delete_avatar_file/' + uuid);
            }
        }
    }); /*end image galey*/
}); /*end doc ready*/
</script>
